site_name: Develop Cloud Connected Mobile Apps with Xamarin and Microsoft Azure
site_url: https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/
repo_url: https://github.com/adrianhall/develop-mobile-apps-with-csharp-and-azure
repo_name: GitHub
site_author: Adrian Hall
pages:
    - Getting Started: index.md
    - Chapter 1 - Introduction:
        - Your First App - PC Edition: chapter1/firstapp_pc.md
        - Your First App - Mac Edition: chapter1/firstapp_mac.md
    - Chapter 2 - Authentication:
        - Concepts: chapter2/authconcepts.md
        - Authentication in the Backend: chapter2/backend.md
        - Enterprise Authentication: chapter2/enterprise.md
        - Social Authentication: chapter2/social.md
        - Debugging Authentication: chapter2/debugging.md
        - Custom Authentication: chapter2/custom.md
        - Claims and Authorization: chapter2/authorization.md
        - Tokens in Real Apps: chapter2/realworld.md
        - Best Practices: chapter2/bestpractices.md
    - Chapter 3 - Data Access and Offline Sync:
        - Concepts: chapter3/dataconcepts.md
        - Implementing Table Controllers: chapter3/server.md
        - Data Projection and Queries: chapter3/projection.md
        - The Mobile Client: chapter3/client.md
        - Relationships: chapter3/relationships.md
        - The Domain Manager: chapter3/domainmgr.md
    - Chapter 4 - Server Side Code:
        - Options: chapter4/options.md
        - Custom API: chapter4/custom.md
        - WebJobs: chapter4/webjobs.md
        - Functions: chapter4/functions.md
    - Chapter 5 - Push Notifications:
        - Concepts: chapter5/concepts.md
        - Notification Hubs: chapter5/nh.md
        - Android Push: chapter5/android.md
        - iOS Push: chapter5/ios.md
        - Windows Push: chapter5/windows.md
        - Testing Push: chapter5/testing.md
        - Push Recipes: chapter5/recipes.md
    - Chapter 6 - File Management:
        - Concepts: chapter6/concepts.md
        - Dealing with Files: chapter6/files.md
        - File Synchronization: chapter6/filesync.md
    - Chapter 7 - Combining Web and Mobile Apps:
        - MVC Applications: chapter7/mvc.md
        - SPA Applications: chapter7/spa.md
    - Chapter 8 - Other Useful Services:
        - Azure Search: chapter8/search.md
        - Media Services: chapter8/media.md
        - Real-time Notifications: chapter8/realtime.md
    - Chapter 9 - Developing An App:
        - The Development Environment: chapter9/developing.md
        - Testing your Application: chapter9/testing.md
    - Chapter 10 - Going to Production:
        - Repeatable Deployments: chapter10/arm.md
        - Safe Deployments: chapter10/appsvc.md
        - Monitoring: chapter10/monitoring.md
        - Troubleshooting: chapter10/troubleshooting.md
    - Xamarin Forms Tips: xamarin_tips.md
    - Android Developer Notes: android_appendix.md
    - References: references.md
    - Credits: credits.md
theme: material
extra:
    author:
      github: 'adrianhall'
      twitter: 'FizzyInTheHall'
markdown_extensions:
    - toc:
        permalink: True
    - fenced_code
    - admonition
extra_css:
  - css/extra.css
  - css/vs.css
extra_javascript:
  - js/highlight.pack.js
