site_name: Develop Cloud Connected Mobile Apps with Xamarin and Microsoft Azure
pages:
- Chapter 1:
  - Introduction: chapter1/index.md
  - Building a Mobile App on Windows: chapter1/firstapp_pc.md
  - Building a Mobile App on a Mac: chapter1/firstapp_mac.md
- Authentication:
  - Concepts: chapter2/index.md
  - Enterprise Authentication: chapter2/enterprise.md
  - Social Authentication: chapter2/social.md
  - Custom Authentication: chapter2/custom.md
  - Claims and Authorization: chapter2/claims.md
  - Refresh and Logout: chapter2/refresh.md
- Data Access and Offline Sync: data.md
- Authenticated Data Access: authdata.md
- File Management: files.md
- Push Notifications: push.md
- Server Side Code: custom.md
- Media Services: media.md
- Leveraging Search: search.md
- Web and Mobile Apps: combined.md
- The Development Environment: developing.md
- Testing your Application: testing.md
- Troubleshooting: troubleshooting.md
- Going to Production: production.md
- Xamarin Forms Tips: xamarin_tips.md
- Android Developer Notes: android_appendix.md
- References: references.md
- Credits: credits.md
theme: readthedocs
extra_css: [extra.css]
