site_name: Develop Cloud Connected Mobile Apps with Xamarin and Microsoft Azure
site_url: https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/
repo_url: https://github.com/adrianhall/develop-mobile-apps-with-csharp-and-azure
repo_name: GitHub
site_author: Adrian Hall
pages:
    - Getting Started: index.md
    - Chapter 1 - Introduction:
        - Your First App - PC Edition: chapter1/firstapp_pc.md
        - Your First App - Mac Edition: chapter1/firstapp_mac.md
    - Chapter 2 - Authentication:
        - Concepts: chapter2/authconcepts.md
        - Authentication in the Backend: chapter2/backend.md
        - Enterprise Authentication: chapter2/enterprise.md
        - Social Authentication: chapter2/social.md
        - Debugging Authentication: chapter2/debugging.md
        - Custom Authentication: chapter2/custom.md
        - Claims and Authorization: chapter2/authorization.md
        - Tokens in Real Apps: chapter2/realworld.md
        - Best Practices: chapter2/bestpractices.md
    - Chapter 3 - Data Access and Offline Sync:
        - Concepts: chapter3/dataconcepts.md
        - Implementing Table Controllers: chapter3/server.md
        - Data Projection and Queries: chapter3/projection.md
        - The Mobile Client: chapter3/client.md
        - Relationships: chapter3/relationships.md
        - The Domain Manager: chapter3/domainmgr.md
    - Chapter 4 - File Management: 
        - Concepts: chapter4/concepts.md
        - Dealing with Files: chapter4/files.md
        - File Synchronization: chapter4/filesync.md
    - Push Notifications: push.md
    - Server Side Code: custom.md
    - Media Services: media.md
    - Leveraging Search: search.md
    - Web and Mobile Apps: combined.md
    - The Development Environment: developing.md
    - Testing your Application: testing.md
    - Troubleshooting: troubleshooting.md
    - Going to Production: production.md
    - Xamarin Forms Tips: xamarin_tips.md
    - Android Developer Notes: android_appendix.md
    - References: references.md
    - Credits: credits.md
theme: material
extra:
    author:
      github: 'adrianhall'
      twitter: 'FizzyInTheHall'
markdown_extensions:
    - toc:
        permalink: True
    - fenced_code
    - admonition
extra_css:
  - css/extra.css
  - css/vs.css
extra_javascript:
  - js/highlight.pack.js
