site_name: Develop Cloud Connected Mobile Apps with Xamarin and Microsoft Azure
pages:
- Introduction: index.md
- Building a Mobile App on Windows: firstapp_pc.md
- Building a Mobile App on a Mac: firstapp_mac.md
- Authentication: authentication.md
- Data Access and Offline Sync: data.md
- Authenticated Data Access: authdata.md
- File Management: files.md
- Push Notifications: push.md
- Server Side Code: custom.md
- Media Services: media.md
- Leveraging Search: search.md
- Web and Mobile Apps: combined.md
- The Development Environment: developing.md
- Testing your Application: testing.md
- Troubleshooting: troubleshooting.md
- Going to Production: production.md
- References: references.md
theme: readthedocs
extra_css: [extra.css]
