site_name: Develop Cloud Connected Mobile Apps with Xamarin and Microsoft Azure
pages:
- Introduction: index.md
- 1. Your First Mobile App: 1_introduction.md
- 2. Authentication: 2_authentication.md
- 3. Data Access and Offline Sync: 3_data.md
- 4. File Management: 4_files.md
- 5. Push Notifications: 5_push.md
- 6. Server Side Code: 6_custom.md
- 7. Media Services: 7_media.md
- 8. Leveraging Search: 8_search.md
- 9. Web and Mobile Apps: 9_combined.md
- 10. The Development Environment: 10_developing.md
- 11. Testing your Application: 11_testing.md
- 12. Troubleshooting: 12_troubleshooting.md
- 13. Going to Production: 13_production.md
- References: references.md
theme: readthedocs
extra_css: [extra.css]
